language: groovy
branches:
    only:
        - master
        - develop
install:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V --settings settings.xml
script:
    - mvn clean test --settings settings.xml
